### ISSUE TITLE
demo基本不能用

### ISSUE THREAD

**Issue by yatoooon** [pili-engineering/QNRTC-Android#12]
视频音频都不行

**Comment by depthlove** [comment]
@yatoooon 出现什么问题了？请提供日志或者截图。

**Comment by KevinHuo** [comment]
@yatoooon 可以的呀，请问您是怎么使用的呢？什么手机型号？

**Comment by yatoooon** [comment]
华为荣耀8  荣耀9i  还有两个android 5.1的手机    都试了一遍

**Comment by yatoooon** [comment]
两台手机     取不同的名字    进同一个房间      就只能显示   join  和 remove 的回调

**Comment by yatoooon** [comment]
有时候  会出现   无数遍这两句回调   08-31 20:37:16.812 16049-16267/com.huichun.expert I/QiniuLiveVideoDetailActivity: onRemoteStreamRemoved: rtc-2
08-31 20:37:17.144 16049-17555/com.huichun.expert I/QiniuLiveVideoDetailActivity: onRemoteStreamAdded: user = rtc-2, hasAudio = true, hasVideo = true, isAudioMuted = false, isVideoMuted = false

**Comment by KevinHuo** [comment]
@yatoooon 没有显示本地和远端的画面对吧？您的 demo 是 github 下扫描二维码下载的吗？

**Comment by yatoooon** [comment]
是的     demo在官网上  和  github上下载的   都运行过了     最多显示到  出现一个对方的小麦克

**Comment by yatoooon** [comment]
本地的画面是有的

**Comment by KevinHuo** [comment]
707786366 方便的话您加我 qq ，我给您联调一下

**Comment by yatoooon** [comment]
感谢老哥
