### ISSUE TITLE
华为手机黑屏问题

### ISSUE THREAD

**Issue by muyishuangfeng** [pili-engineering/QNRTC-Android#28]
华为手机当打开系统相机的时候，再进入到应用中，会显示黑屏。

**Comment by haiyangwu** [comment]
您好，在您的业务需要打开系统相机前调用 QNRTCEngine#stopCapture 方法让 SDK 释放相机资源，使用完系统相机后再调用 QNRTCEngine#startCapture 方法让 SDK 再次获取相机资源。但 2.1.0 的版本 SDK 内部处理有 BUG 会导致画面停帧。2.1.1 版本会修复，如果急需灰度版本可以加我 QQ ：545945170

**Comment by muyishuangfeng** [comment]
嗯，好的，谢谢，我用了另外一种方式解决了。
