### ISSUE TITLE
关于自定义消息功能

### ISSUE THREAD

**Issue by fectong** [pili-engineering/QNRTC-Android#35]
文档应用场景里提到  

> 5 在线教育 - 自定义消息
> 6 在线抓娃娃 - 操控指令

但是没有在 API 文档种找到相应的介绍, 能提供些详细的文档么 ?

**Comment by OurEra** [comment]
https://doc.qnsdk.com/rtn/android/docs/api_qnrtcengine
QNRTCEngine#sendMessage

https://doc.qnsdk.com/rtn/android/docs/api_qnrtcengineeventlistener
QNRTCEngineEventListener#onMessageReceived
