### ISSUE TITLE
PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer

### ISSUE THREAD

**Issue by llllonger** [pili-engineering/QNRTC-Android#38]
06-28 16:57:00.864 18287-19008/com.miyue.lives E/peerconnection.cc: (line 1883): PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.
06-28 16:57:00.864 18287-19008/com.miyue.lives A/libc: /usr/local/google/buildbot/src/android/ndk-release-r16/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "Pure virtual function called!" failed

**Comment by OurEra** [comment]
pls use latest release version
