### ISSUE TITLE
pushAudioBuffer 重采样闪退

### ISSUE THREAD

**Issue by ShaoYuzhen** [pili-engineering/QNRTC-Android#56]
QNAudioFormat mQNAudioFormat =new QNAudioFormat(QNAudioFormat.SAMPLE_CHANNEL_MONO_COUNT, 44100, AudioFormat.ENCODING_PCM_16BIT)
QNRTCEngine.pushAudioBuffer(audioData, mQNAudioFormat);
报错闪退，log如下

1 #00 pc 000175c8 /system/lib/libc.so (memcpy+96) [armeabi-v7a]
2 #01 pc 00176397 /data/app/***/lib/arm/libqndroid_rtc.so [armeabi]
3 #02 pc 00175ba9 /data/app/***/lib/arm/libqndroid_rtc.so [armeabi]
4 #03 pc 0019fb41 /data/app/***/lib/arm/libqndroid_rtc.so [armeabi]
5 #04 pc 000ae519 /system/lib/libart.so (art_quick_generic_jni_trampoline+40) [armeabi-v7a]
6 #05 pc cc06c829 <unknown>
7 java:
8 org.webrtc.audio.WebRtcAudioRecord.void inputExternalAudioFrame(byte[])(WebRtcAudioRecord.java:25)
9 org.webrtc.audio.JavaAudioDeviceModule.void inputExternalAudioFrame(byte[])(JavaAudioDeviceModule.java:2)
10 com.qiniu.droid.rtc.renderer.audio.eyd3OXAZgV.void a(byte[])(RTCAudioManager.java:49)
11 com.qiniu.droid.rtc.Wja3o2vx62.eyd3OXAZgV.void pushAudioBuffer(byte[],com.qiniu.droid.rtc.QNAudioFormat)(RTCEngineImpl.java:6)

**Comment by OurEra** [comment]
请更新至最新版本
