### ISSUE TITLE
qndroid-rtc-3.0.0.jar和涂鸦的库混淆后冲突了

### ISSUE THREAD

**Issue by luoqiang108** [pili-engineering/QNRTC-Android#59]
Duplicate class a.a.a.a.a found in modules jetified-qndroid-rtc-3.0.0.jar (qndroid-rtc-3.0.0.jar) and jetified-tuyasmart-ipc-camera-v2-3.25.0-open-runtime.jar (com.tuya.smart:tuyasmart-ipc-camera-v2:3.25.0-open)

**Comment by OurEra** [comment]
升级最新3.0.2即可。
