### ISSUE TITLE
demo编译运行时报错

### ISSUE THREAD

**Issue by csspark** [pili-engineering/QNRTC-Android#6]
IDE：Android studio 3.1.3
报错文件：RoomActivity.java

错误: <匿名com.qiniu.droid.rtc.demo.activity.RoomActivity$1>不是抽象的, 并且未覆盖QNRemoteAudioCallback中的抽象方法onData(String,ByteBuffer,int,int,int,int) |  
-- | --
错误: 方法不会覆盖或实现超类型的方法 |  
错误: <匿名com.qiniu.droid.rtc.demo.activity.RoomActivity$11>不是抽象的, 并且未覆盖QNRemoteAudioCallback中的抽象方法onData(String,ByteBuffer,int,int,int,int) |  
错误: 方法不会覆盖或实现超类型的方法 |

**Comment by willnew** [comment]
删掉onData，重写QNRemoteAudioCallback里面那个唯一的方法，就可以正常运行了
